// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWijqwPDhqycUKm9QP8qkP9qb1-XnDdYM',
    appId: '1:272385044432:web:524b744f86942b570053d5',
    messagingSenderId: '272385044432',
    projectId: 'matchquest-d5c46',
    authDomain: 'matchquest-d5c46.firebaseapp.com',
    storageBucket: 'matchquest-d5c46.firebasestorage.app',
    measurementId: 'G-CX1B4EK3LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVnMwR7W4eN4FG260wfWuSGsRDmZxsFaI',
    appId: '1:272385044432:android:a6f2aba5d484ea4b0053d5',
    messagingSenderId: '272385044432',
    projectId: 'matchquest-d5c46',
    storageBucket: 'matchquest-d5c46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo37j7oY_gIXmBYqnCdLYlPwjQkoGHfZY',
    appId: '1:272385044432:ios:6533b4d2c57d319d0053d5',
    messagingSenderId: '272385044432',
    projectId: 'matchquest-d5c46',
    storageBucket: 'matchquest-d5c46.firebasestorage.app',
    androidClientId: '272385044432-8b8f07b24iha5i7slencno52fbekdt58.apps.googleusercontent.com',
    iosClientId: '272385044432-rbb90rau2uckkvpk5359l8ch98i9nrd2.apps.googleusercontent.com',
    iosBundleId: 'com.match.quest.matchquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo37j7oY_gIXmBYqnCdLYlPwjQkoGHfZY',
    appId: '1:272385044432:ios:6533b4d2c57d319d0053d5',
    messagingSenderId: '272385044432',
    projectId: 'matchquest-d5c46',
    storageBucket: 'matchquest-d5c46.firebasestorage.app',
    androidClientId: '272385044432-8b8f07b24iha5i7slencno52fbekdt58.apps.googleusercontent.com',
    iosClientId: '272385044432-rbb90rau2uckkvpk5359l8ch98i9nrd2.apps.googleusercontent.com',
    iosBundleId: 'com.match.quest.matchquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWijqwPDhqycUKm9QP8qkP9qb1-XnDdYM',
    appId: '1:272385044432:web:01f105a9227596070053d5',
    messagingSenderId: '272385044432',
    projectId: 'matchquest-d5c46',
    authDomain: 'matchquest-d5c46.firebaseapp.com',
    storageBucket: 'matchquest-d5c46.firebasestorage.app',
    measurementId: 'G-L46Y46DWSH',
  );

}